import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Navigation from './component/navigation/navigation.component';


export default function Home() {
  const [isConnect, setIsConnect] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify wish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation isConnected={isConnect} />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue dans notre bibliothèque de Musique 
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' Marc-antoine SIMON'}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
